apiVersion: apps/v1
kind: Deployment
metadata:
  name: tvanurag-eta-deploy
  labels:
    app: tvanurag-eta-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tvanurag-eta-app
  template:
    metadata:
      labels:
        app: tvanurag-eta-app
    spec:
      containers:
      - name: tvanurag-eta-app
        image: tvanurag/mydevops-eta-app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tvanurag-eta-np-service
  labels:
    app: tvanurag-eta-app
spec:
  selector:
    app: tvanurag-eta-app

  type: NodePort
  ports:
  - nodePort: 31028
    port: 8080
    targetPort: 8080
